name: Upload Model from CivitAI to Hugging Face

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  upload-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests huggingface_hub

      - name: Check for new models
        run: |
          python check_civitai_models.py

      - name: Debug environment variable
        run: |
          echo "NEW_MODEL_FOUND: $NEW_MODEL_FOUND"

      - name: Debug files
        run: |
          echo "Latest Model ID: $(cat latest_model_id.txt)"
          echo "Latest Version ID: $(cat latest_version_id.txt)"
          echo "Latest File Format: $(cat latest_file_format.txt)"

      - name: Download model from CivitAI
        if: env.NEW_MODEL_FOUND == 'true'
        run: |
          MODEL_ID=$(cat latest_model_id.txt)
          VERSION_ID=$(cat latest_version_id.txt)
          FILE_FORMAT=$(cat latest_file_format.txt)
          CIVITAI_TOKEN=${{ secrets.CIVITAI_TOKEN }}
          
          if [[ -z "$VERSION_ID" ]]; then
            DOWNLOAD_URL="https://civitai.com/api/download/models/$MODEL_ID?type=Model&format=$FILE_FORMAT&token=$CIVITAI_TOKEN"
          else
            DOWNLOAD_URL="https://civitai.com/api/download/models/$VERSION_ID?type=Model&format=$FILE_FORMAT&token=$CIVITAI_TOKEN"
          fi
          
          echo "Download URL: $DOWNLOAD_URL"
          curl -L -o "model.$FILE_FORMAT" "$DOWNLOAD_URL"
          echo "Model downloaded successfully!"

      - name: Upload model to Hugging Face
        if: env.NEW_MODEL_FOUND == 'true'
        run: |
          FILE_FORMAT=$(cat latest_file_format.txt)
          python upload_to_huggingface.py --model_path "model.$FILE_FORMAT" --repo_id ${{ secrets.HF_REPO_ID }} --token ${{ secrets.HF_TOKEN }}
